version: "3.8"

services:
  mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./.env:/usr/src/app/.env
    restart: unless-stopped
